apiVersion: apps/v1
kind: Deployment
metadata:
  name: amor
  labels:
    app: amor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amor
  template:
    metadata:
      labels:
        app: amor
    spec:
      containers:
        - name: amor
          image: ghcr.io/ibtisam-iq/amor:latest
          ports:
            - containerPort: 8081
              # hostPort: 8081 
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: amor
  labels:
    app: amor
spec:
  selector:
    app: amor
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081 
      nodePort: 30000
  type: NodePort